CREATE TABLE MARCHE 
(
	idMarca INT IDENTITY(1, 1) PRIMARY KEY,
	marca VARCHAR(50) NOT NULL
);

CREATE TABLE ALIMENTAZIONI
(
	idAl INT IDENTITY(1, 1) PRIMARY KEY,
	alimentazione VARCHAR(50) NOT NULL
);

CREATE TABLE MODELLI
(
	idModello INT IDENTITY(1, 1) PRIMARY KEY,
	modello VARCHAR(50) NOT NULL,
	idMarca INT NOT NULL,
	FOREIGN KEY (idMarca) REFERENCES
		MARCHE(idMarca)
);

CREATE TABLE CLIENTI
(
	idCliente INT IDENTITY(1, 1) PRIMARY KEY,
	cognome VARCHAR(50) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	telefono VARCHAR(15),
	email VARCHAR(50)
);

CREATE TABLE AUTOMOBILI
(
	targa VARCHAR(10) PRIMARY KEY,
	km INT NOT NULL,
	colore VARCHAR(50) NOT NULL,
	cambioAutomatico BIT DEFAULT 0,
	disponibile BIT DEFAULT 1,
	idModello INT NOT NULL,
	idAl INT NOT NULL,
	FOREIGN KEY (idModello) REFERENCES
		MODELLI(idModello),
	FOREIGN KEY (idAl) REFERENCES
		ALIMENTAZIONI(idAl)
);

CREATE TABLE NOLEGGI
(
	idNoleggio INT IDENTITY(1, 1) PRIMARY KEY,
	targa VARCHAR(10) NOT NULL,
	idCliente INT NOT NULL,
	dataInizio DATE DEFAULT GETDATE(),
	dataFine DATE,
	FOREIGN KEY (targa) REFERENCES
		AUTOMOBILI(targa),
	FOREIGN KEY (idCliente) REFERENCES
		CLIENTI(idCliente)
);