--auto con kilometri superiori alla media
SELECT AVG(km) as 'media' FROM AUTOMOBILI
SELECT * FROM AUTOMOBILI
SELECT * FROM AUTOMOBILI
WHERE km > (SELECT AVG(km) FROM AUTOMOBILI);

--tutti i dati delle auto MAI noleggiate
SELECT A.* FROM NOLEGGI N
RIGHT JOIN AUTOMOBILI A ON N.targa=A.TARGA
WHERE N.idNoleggio IS NULL

--tutti i dati delle auto noleggiate IN GIORNATA
SELECT A.* FROM NOLEGGI N
RIGHT JOIN AUTOMOBILI A ON N.targa=A.TARGA
WHERE N.dataInizio=CAST(GETDATE() AS DATE)

--NUMERO delle AUTO con la STESSA MARCA SE il NUMERO è MAGGIORE di UNO
SELECT MA.marca,COUNT(A.targa) AS 'N. AUTO DISPONIBILI' 
FROM AUTOMOBILI A
FULL JOIN MODELLI M ON A.idModello=M.idModello
FULL JOIN MARCHE MA ON M.idMarca=MA.idMarca
WHERE A.disponibile=1
GROUP BY MA.marca
HAVING COUNT(A.targa)>1

--NUMERO delle AUTO già RESTITUITE PER OGNI CLIENTE
SELECT C.cognome,count(N.dataFine) as 'N. RESTITUZIONI' FROM NOLEGGI N
FULL JOIN CLIENTI C ON N.idCliente=C.idCliente
GROUP BY C.cognome

--NUMERO DI MERCEDEZ
--SELECT COUNT (A.idModello) AS 'N. MERCEDEZ' 
SELECT count(a.targa) as 'N. MERCEDES-NERO-GASOLIO'
FROM AUTOMOBILI A
LEFT JOIN MODELLI M ON A.idModello=M.idModello
LEFT JOIN MARCHE MA ON M.idMarca=MA.idMarca
LEFT JOIN ALIMENTAZIONI AL ON A.idAl=AL.idAl
WHERE MA.marca='MERCEDES' AND A.colore='NERO' AND AL.alimentazione='GASOLIO'
